//
//  main.cpp
//  Assignment3
//
//  Created by Yusra Khalid on 12/31/17.
//  Copyright © 2017 Yusra Khalid. All rights reserved.
//

#include "hashTables.hpp"
#include "avl.hpp"
#include <iostream>

int main(int argc, const char * argv[]) {
    hashTables h;
    string nTH[] = {"AENA HASSAN","AGHA SAAD FRAZ","ALISHBA SHAHID","AREESHA TARIQ","FAIZAN SHAHID","FARRUKH BIN RASHID SIDDIQUI","HADIQA ALAMDAR BUKHARI","HAFIZ MUHAMMAD ASAAD IQBAL","HAFIZ MUHAMMAD HASSAN TARIQ","HALEEMA KHAN","HAMMAD AAMER","HAMNA MOIEEZ","HAMZA KHURSHID","HIBA AKRAM","IMAMA JAWAD","INSHAL SALEEM","KHADIJA KAMRAN","MAHAD MASOOD BAJWA","MAHEER FAROOQ","MARIA AHMED","MOHAMMAD ZIAD SIDDIQUI","MOMIN MUAZZAM","MUHAMMAD HAMAAD LATIF","MUHAMMAD MUNEEB SHAHRYAR","MUHAMMAD QAISER","MUHAMMAD UZAIR","NADIR ALI","NOOR ALVI","NOOR BINTE AMIR","OSAMA JAMIL","ROSHEEN NAEEM","SHABEEH FATIMA CHAUDRY"," BIN ABDUL BARI","SYED TALAL MUSHARRAF","SYED WALEED HYDER","TAIMUR AZHAR","URVAH SAIKHANI","YUSRA MASOOD","ZAEEM HABIB","ABDUL RAHEEM","AMEER HAMZA","ASAD AWAN","AYESHA MUKHTAR","BIA CHAUDHRY","FARHANA SHAFI","HAMZA IQBAL","HANIYA HUDA","HIBBA FATIMA","HIRA TANVEER","HULMA NASEER","HUSSAIN NAWAZ LALEE","JAWAD ZAHEER","KAFAITE ZAHRA HUSSAIN","KASHIF NAZIR KHAN","MUHAMMAD AHMAD","MUHAMMAD AHMED SHAHRYAR","MUHAMMAD AHSAN","MUHAMMAD AHSAN FAROOQ","MUHAMMAD AMIR","MUHAMMAD HARIS LATIF","MUHAMMAD JUNAID KHALID","MUHAMMAD MUSTAFA SIDDIQI","MUHAMMAD SAAD","MUHAMMAD TALHA ABBAS","MUHAMMAD ZOHAIB","MUHAMMED MUSTAFA AWWAL","NAEMA ASIF","NIMRA.","NOSHERWAN AKRAM","NOUMAN AHMED","RAHAT UL AIN","RAMSHA IFTIKHAR","Ramlah Aamir Aziz","SADIA NASEER","SHEHERYAR IQBAL","SOHAIB AZHAR","SYED MUHAMMAD DANIYAL KHALID","TASMIA BATOOL CHISHTI","UBAID UR REHMAN","WALI ULLAH RAZA","YUSRA KHALID","ZEYAD AHMED","-1"};
    
    int i = 0;
    while (nTH[i] != "-1" ){
        h.insert(h, nTH[i]);
        i++;
    }
    
    h.display();
    return 0;
}
